### ISSUE TITLE
docker-compose version 2

### ISSUE THREAD

**Issue by rokka-n** [zuazo/specinfra-backend-docker_compose#1]
Hi,

Thanks for writing this useful gem! 
Is it supposed to work with first version of docker-compose only?

**Comment by zuazo** [comment]
You are welcome :wink:

I'm using the [`docker-compose-api`](https://github.com/mauricioklein/docker-compose-api) gem. At least some basic things of v2 are supported.

See the following links for more information:
- [docker-compose file v2 (docker-compose v1.6) compatibility](https://github.com/mauricioklein/docker-compose-api/issues/21)
- [Add Basic Support for V2 Docker-Compose Configs](https://github.com/mauricioklein/docker-compose-api/issues/26)
